/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedPropostasRouteImport } from './routes/_authenticated/propostas'
import { Route as AuthenticatedContratosRouteImport } from './routes/_authenticated/contratos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedPropostasIdRouteImport } from './routes/_authenticated/propostas.$id'
import { Route as AuthenticatedContratosIdRouteImport } from './routes/_authenticated/contratos.$id'
import { Route as AuthenticatedPropostasIdDocumentoRouteImport } from './routes/_authenticated/propostas.$id.documento'
import { Route as AuthenticatedContratosIdDocumentoRouteImport } from './routes/_authenticated/contratos.$id.documento'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/_authenticated/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropostasRoute = AuthenticatedPropostasRouteImport.update({
  id: '/_authenticated/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedContratosRoute = AuthenticatedContratosRouteImport.update({
  id: '/_authenticated/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/_authenticated/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/_authenticated/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPropostasIdRoute =
  AuthenticatedPropostasIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPropostasRoute,
  } as any)
const AuthenticatedContratosIdRoute =
  AuthenticatedContratosIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedContratosRoute,
  } as any)
const AuthenticatedPropostasIdDocumentoRoute =
  AuthenticatedPropostasIdDocumentoRouteImport.update({
    id: '/documento',
    path: '/documento',
    getParentRoute: () => AuthenticatedPropostasIdRoute,
  } as any)
const AuthenticatedContratosIdDocumentoRoute =
  AuthenticatedContratosIdDocumentoRouteImport.update({
    id: '/documento',
    path: '/documento',
    getParentRoute: () => AuthenticatedContratosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/servicos': typeof AuthenticatedServicosRoute
  '/': typeof AuthenticatedIndexRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/propostas/$id': typeof AuthenticatedPropostasIdRouteWithChildren
  '/contratos/$id/documento': typeof AuthenticatedContratosIdDocumentoRoute
  '/propostas/$id/documento': typeof AuthenticatedPropostasIdDocumentoRoute
}
export interface FileRoutesByTo {
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/servicos': typeof AuthenticatedServicosRoute
  '/': typeof AuthenticatedIndexRoute
  '/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/propostas/$id': typeof AuthenticatedPropostasIdRouteWithChildren
  '/contratos/$id/documento': typeof AuthenticatedContratosIdDocumentoRoute
  '/propostas/$id/documento': typeof AuthenticatedPropostasIdDocumentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/contratos': typeof AuthenticatedContratosRouteWithChildren
  '/_authenticated/propostas': typeof AuthenticatedPropostasRouteWithChildren
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/contratos/$id': typeof AuthenticatedContratosIdRouteWithChildren
  '/_authenticated/propostas/$id': typeof AuthenticatedPropostasIdRouteWithChildren
  '/_authenticated/contratos/$id/documento': typeof AuthenticatedContratosIdDocumentoRoute
  '/_authenticated/propostas/$id/documento': typeof AuthenticatedPropostasIdDocumentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/propostas'
    | '/servicos'
    | '/'
    | '/contratos/$id'
    | '/propostas/$id'
    | '/contratos/$id/documento'
    | '/propostas/$id/documento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/propostas'
    | '/servicos'
    | '/'
    | '/contratos/$id'
    | '/propostas/$id'
    | '/contratos/$id/documento'
    | '/propostas/$id/documento'
  id:
    | '__root__'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/contratos'
    | '/_authenticated/propostas'
    | '/_authenticated/servicos'
    | '/_authenticated/'
    | '/_authenticated/contratos/$id'
    | '/_authenticated/propostas/$id'
    | '/_authenticated/contratos/$id/documento'
    | '/_authenticated/propostas/$id/documento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedContratosRoute: typeof AuthenticatedContratosRouteWithChildren
  AuthenticatedPropostasRoute: typeof AuthenticatedPropostasRouteWithChildren
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/propostas': {
      id: '/_authenticated/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof AuthenticatedPropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/contratos': {
      id: '/_authenticated/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof AuthenticatedContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/propostas/$id': {
      id: '/_authenticated/propostas/$id'
      path: '/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof AuthenticatedPropostasIdRouteImport
      parentRoute: typeof AuthenticatedPropostasRoute
    }
    '/_authenticated/contratos/$id': {
      id: '/_authenticated/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof AuthenticatedContratosIdRouteImport
      parentRoute: typeof AuthenticatedContratosRoute
    }
    '/_authenticated/propostas/$id/documento': {
      id: '/_authenticated/propostas/$id/documento'
      path: '/documento'
      fullPath: '/propostas/$id/documento'
      preLoaderRoute: typeof AuthenticatedPropostasIdDocumentoRouteImport
      parentRoute: typeof AuthenticatedPropostasIdRoute
    }
    '/_authenticated/contratos/$id/documento': {
      id: '/_authenticated/contratos/$id/documento'
      path: '/documento'
      fullPath: '/contratos/$id/documento'
      preLoaderRoute: typeof AuthenticatedContratosIdDocumentoRouteImport
      parentRoute: typeof AuthenticatedContratosIdRoute
    }
  }
}

interface AuthenticatedContratosIdRouteChildren {
  AuthenticatedContratosIdDocumentoRoute: typeof AuthenticatedContratosIdDocumentoRoute
}

const AuthenticatedContratosIdRouteChildren: AuthenticatedContratosIdRouteChildren =
  {
    AuthenticatedContratosIdDocumentoRoute:
      AuthenticatedContratosIdDocumentoRoute,
  }

const AuthenticatedContratosIdRouteWithChildren =
  AuthenticatedContratosIdRoute._addFileChildren(
    AuthenticatedContratosIdRouteChildren,
  )

interface AuthenticatedContratosRouteChildren {
  AuthenticatedContratosIdRoute: typeof AuthenticatedContratosIdRouteWithChildren
}

const AuthenticatedContratosRouteChildren: AuthenticatedContratosRouteChildren =
  {
    AuthenticatedContratosIdRoute: AuthenticatedContratosIdRouteWithChildren,
  }

const AuthenticatedContratosRouteWithChildren =
  AuthenticatedContratosRoute._addFileChildren(
    AuthenticatedContratosRouteChildren,
  )

interface AuthenticatedPropostasIdRouteChildren {
  AuthenticatedPropostasIdDocumentoRoute: typeof AuthenticatedPropostasIdDocumentoRoute
}

const AuthenticatedPropostasIdRouteChildren: AuthenticatedPropostasIdRouteChildren =
  {
    AuthenticatedPropostasIdDocumentoRoute:
      AuthenticatedPropostasIdDocumentoRoute,
  }

const AuthenticatedPropostasIdRouteWithChildren =
  AuthenticatedPropostasIdRoute._addFileChildren(
    AuthenticatedPropostasIdRouteChildren,
  )

interface AuthenticatedPropostasRouteChildren {
  AuthenticatedPropostasIdRoute: typeof AuthenticatedPropostasIdRouteWithChildren
}

const AuthenticatedPropostasRouteChildren: AuthenticatedPropostasRouteChildren =
  {
    AuthenticatedPropostasIdRoute: AuthenticatedPropostasIdRouteWithChildren,
  }

const AuthenticatedPropostasRouteWithChildren =
  AuthenticatedPropostasRoute._addFileChildren(
    AuthenticatedPropostasRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedContratosRoute: AuthenticatedContratosRouteWithChildren,
  AuthenticatedPropostasRoute: AuthenticatedPropostasRouteWithChildren,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
