/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as PropostasRouteImport } from './routes/propostas'
import { Route as ContratosRouteImport } from './routes/contratos'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'
import { Route as ContratosIdRouteImport } from './routes/contratos.$id'

const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasRoute = PropostasRouteImport.update({
  id: '/propostas',
  path: '/propostas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratosRoute = ContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropostasRoute,
} as any)
const ContratosIdRoute = ContratosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContratosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/propostas': typeof PropostasRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/propostas/$id': typeof PropostasIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/propostas': typeof PropostasRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/propostas/$id': typeof PropostasIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contratos': typeof ContratosRouteWithChildren
  '/propostas': typeof PropostasRouteWithChildren
  '/servicos': typeof ServicosRoute
  '/contratos/$id': typeof ContratosIdRoute
  '/propostas/$id': typeof PropostasIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/propostas'
    | '/servicos'
    | '/contratos/$id'
    | '/propostas/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/propostas'
    | '/servicos'
    | '/contratos/$id'
    | '/propostas/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/configuracoes'
    | '/contratos'
    | '/propostas'
    | '/servicos'
    | '/contratos/$id'
    | '/propostas/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContratosRoute: typeof ContratosRouteWithChildren
  PropostasRoute: typeof PropostasRouteWithChildren
  ServicosRoute: typeof ServicosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas': {
      id: '/propostas'
      path: '/propostas'
      fullPath: '/propostas'
      preLoaderRoute: typeof PropostasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratos': {
      id: '/contratos'
      path: '/contratos'
      fullPath: '/contratos'
      preLoaderRoute: typeof ContratosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof PropostasRoute
    }
    '/contratos/$id': {
      id: '/contratos/$id'
      path: '/$id'
      fullPath: '/contratos/$id'
      preLoaderRoute: typeof ContratosIdRouteImport
      parentRoute: typeof ContratosRoute
    }
  }
}

interface ContratosRouteChildren {
  ContratosIdRoute: typeof ContratosIdRoute
}

const ContratosRouteChildren: ContratosRouteChildren = {
  ContratosIdRoute: ContratosIdRoute,
}

const ContratosRouteWithChildren = ContratosRoute._addFileChildren(
  ContratosRouteChildren,
)

interface PropostasRouteChildren {
  PropostasIdRoute: typeof PropostasIdRoute
}

const PropostasRouteChildren: PropostasRouteChildren = {
  PropostasIdRoute: PropostasIdRoute,
}

const PropostasRouteWithChildren = PropostasRoute._addFileChildren(
  PropostasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContratosRoute: ContratosRouteWithChildren,
  PropostasRoute: PropostasRouteWithChildren,
  ServicosRoute: ServicosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
